- cmd/switcher/switcher.go
This is a documented feature https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/kubeconfig_stores.md#specify-the-kubeconfig-name-pattern-to-search-for but there was no code for it, so there it is :)
> add support for kubeconfigname at store level

- pkg/store/kubeconfig_store_eks.go
Right now eks store fails with `error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"`
More info here: https://github.com/aws/aws-cli/issues/6920
> fix invalid apiVersion

- docs/installation.md
- docs/kubeconfig_stores.md
Just a few things that I found with my initial setup of the tool. I don't have a `~/.kube/config` file since its default context could dangerously point to a production cluster. Therefore, an example for a simplistic kubeswitch config file was added and the error case is now explained in the installation guide. Also some Markdown lint fixes (only one h1 heading, no trailing whitespace, etc.).
> Clarify bashrc installation and configuration if user does not have a `~/.kube/config` file

- docs/stores/filesystem/filesystem.md
I've fixed a typo in the filesystem docs.
> fix: typo in filesystem docs

- docs/stores/rancher/rancher.md
- pkg/store/kubeconfig_store_rancher.go
- types/config.go
While setting up the Rancher store I've noticed that the sample in the docs uses the `rancherAddress`  map key, while the code expects the key to be `rancherAPIAddress`. I've fixed the docs as well as renamed the variable in the go code to use the same name just to make it more clear. Also updated the wording on the Rancher store docs a bit.
Tests still passing and there are no functional changes.
> fix: rancher address config var and docs mismatch

- hack/switch/switch.sh
This fixes `--version` flag and fixes behaviour of the flags vs. `version` command.
Before / after:
```diff
$ switch -v
-Switch:
-		version     : v0.7.2
-		build date  : 2022-09-20
-		go version  : go1.19
-		go compiler : gc
-		platform    : linux/amd64
+switch version v0.7.2
$ switch --version
-W0206 01:24:46.618960  341653 loader.go:222] Config not found: switch version v0.7.2
-error: current-context is not set
-switched to context "".
+switch version v0.7.2
```
Output of `switch version` stays the same.
> fix: version flag in switch.sh

- docs/stores/eks/eks.md
Intended to fix the Markdown link to create Kube config and fixed the
other markdownlint warnings (except line length).
Signed-off-by: Stephen Hoekstra <shoekstra@schubergphilis.com>
> docs(EKS Store): Fix Markdown

- hack/switch/switch.fish
- hack/switch/switch.sh
As I use an alias for rm commands, (alises to rip), an error appear every time I try to change my context
```
➜  switch git:(master) switch tools
error: Found argument '-f' which wasn't expected, or isn't valid in this context
```
I've made this commit to force raw command
> change(switch): dont use alias for rm command

- cmd/switcher/init.go
Using backslash in fish to prevent alias expansion does not work (`fish: Unknown command: \rm`).  
Instead you need to use `command`: https://github.com/fish-shell/fish-shell/issues/5076#issuecomment-401511602
> fix(fish): fix 'rm' command unalias

- hack/switch/switch.fish
Fixes #124 
The main bug was fixed already in #121.
This PR fixes the code in `hack/switch/switch.fish`, where the problem still exists.
> fix: calling `rm` command in hack/switch/switch.fish

- pkg/store/kubeconfig_store_vault.go
I found that I have a Vault path that has no data (which is something I should get cleaned up). When configured with a filesystem cache, this result from Vault with empty data results in the following error when running `switch list-contexts`:
```
panic: runtime error: index out of range [0] with length 0
goroutine 24 [running]:
github.com/danielfoehrkn/kubeswitch/pkg/util/kubectx_copied.New({0x366a480, 0x0, 0x0}, {0xc000750cc0, 0x57}, 0x0)
kubeswitch/pkg/util/kubectx_copied/kubeconfig.go:73 +0x11c
github.com/danielfoehrkn/kubeswitch/pkg/cache/file.(*fileCache).GetKubeconfigForPath(0xc0006d0900, {0xc0003bc060, 0x1d}, 0x0)
kubeswitch/pkg/cache/file/fileCache.go:137 +0x2bc
github.com/danielfoehrkn/kubeswitch/pkg.DoSearch.func4({0x249fcd8, 0xc0006d0900}, 0xc000058480, {0xc00047a4d0, …
```
> Fail if Vault data is empty

- docs/installation.md
Complection with alias not working on swithcer 0.9.1 due to base function name changes
> Fix alias bash completion in README

- pkg/store/kubeconfig_store_file.go
Just a little flag /on to follow symlinks in path set in the switch-config.
I don't think there is an issue to having it /on.
> fix 🐛(kubeconfig filesystem store): kubeswitch follows symlinks

- cmd/switcher/namespace.go
- pkg/subcommands/ns/ns.go
We have a tool that chooses a cluster and namespace based on runtime data, and
by the time we have decided what cluster and namespace to connect to, we already
know that the namespace exists in the cluster.
We want to extend this tool to support multiple switching mechanisms (rather than
just `kubectl config use-context` and `kubectl config set-context`), and but the
existence check for the namespace is prohibitively slow on some of our clusters.
To avoid paying that penalty, this change adds a flag to `switch ns` which allows
the user to opt out of the existence check.
```
λ switch ns does-not-exist
namespace "does-not-exist" not foundexit status 1
λ switch ns does-not-exist --check-existence=false
```
> Add flag to opt out of existence check when switching namespaces

- pkg/subcommands/ns/ns.go
This PR increases the rate limits (QPS and burst) of the namespace switching component. This fixes the issue of the namespace switcher timing out while fetching the namespaces from a cluster due to cache discovery of the kubernetes API / client-go taking too long on clusters with lots of CRDs. This is a known issue, cf. [this blog post from 2022](https://jonnylangefeld.com/blog/the-kubernetes-discovery-cache-blessing-and-curse) and other users have also reported issues for similar timeouts in #127.
I've updated QPS to `50.0` and burst to `300` from the defaults specified in https://github.com/danielfoehrKn/kubeswitch/blob/a6981cf4bded76d22ffc2ec8919b1e0d528c1f23/vendor/k8s.io/client-go/rest/config.go#L43-L46
The default burst for cache discovery is set in …
> fix(namespaces): increase QPS and burst rate limits

- docs/stores/capi/capi.md
- pkg/store/kubeconfig_store_capi.go
- types/config.go
This PR allows you to passively search any cluster in your current context for CAPI clusters if a kubeconfigPath is not defined. This makes this store more flexible as mgmt clusters are deleted, created, and switched between. Open to any feedback on any explanations or implementations here. an alternative to this is we could add an explicit `useCurrentContext: true` bool or something like that
> add support for searching for CAPI clusters in the current context

- pkg/store/kubeconfig_store_gke.go
When using the GKE DNS Endpoint, GCP uses a different CA, Google Trust Service, LLC, to sign the certificate.  Since this CA is publicly trusted, there is no need to set CA here.
The GKE API Authentication documentation only mention getting CA data when using IP-based endpoints:
https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#environments-without-gcloud
> fix: Removes GKE CA Data when using DNS Endpoint

- pkg/store/kubeconfig_store_akamai.go
This pull request includes an important change to the `GetID` method in the `AkamaiStore` struct in the `pkg/store/kubeconfig_store_akamai.go` file. The change ensures that the store ID is dynamically determined based on the presence of an ID in the `KubeconfigStore`.
Key change:
* [`pkg/store/kubeconfig_store_akamai.go`](diffhunk://#diff-c32bb69d6c62ce3ddd5494633e9d77b86aa27b15ed385d1c2211b3608c5bd144L86-R92): Modified the `GetID` method to check if `KubeconfigStore.ID` is not nil and use its value; otherwise, it defaults to "default". This ensures a more flexible and accurate ID generation.
> fix: manage id in akamai store

- pkg/store/kubeconfig_store_plugins.go
This pull request includes a change to the `GetID` method in the `pkg/store/kubeconfig_store_plugins.go` file to improve the handling of the `ID` field.
* Modified the `GetID` method to use a local `ID` from `KubeconfigStore` if available, defaulting to "default" otherwise.
> fix(plugin): manage multiple local ID

- cmd/switcher/show.go
- pkg/subcommands/show/show.go
This pull request introduces a new `show` command to the Kubeswitch tool, which allows users to display the kubeconfig for a specified context. The changes include the creation of a new command file and the implementation of the corresponding functionality to retrieve and display the kubeconfig.
New command implementation:
* [`cmd/switcher/show.go`](diffhunk://#diff-4195d48d918a75f649b44cc13ab8d4d5896f695eeeab154730047e8dc18c1101R1-R48): Added a new `show` command that initializes the necessary components and displays the kubeconfig for the specified context.
Functionality to retrieve kubeconfig:
* [`pkg/subcommands/show/show.go`](diffhunk://#diff-4b3f7e7293a29916d53d63f4a23ec53bb79cf90b7524ec2ebf8fa372ed5e189dR1-R51): Implemented the `Show` function, which searches for the specified …
> feat: add "show" command

- docs/installation.md
The 's' alias setup in the zsh installation docs is not taking effect. This pull request corrects the docs.
> docs: Correcting the zsh installation documentation
